name: SimpleQuery CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]
        ar-gemfile: ["activerecord7.0", "activerecord7.1", "activerecord7.2", "activerecord8.0"]
        exclude:
          # ActiveRecord 7.2 => requires Ruby >= 3.1
          - ruby-version: "2.7"
            ar-gemfile: "activerecord7.2"
          - ruby-version: "3.0"
            ar-gemfile: "activerecord7.2"

          # ActiveRecord 8 => requires Ruby >= 3.2
          - ruby-version: "2.7"
            ar-gemfile: "activerecord8.0"
          - ruby-version: "3.0"
            ar-gemfile: "activerecord8.0"
          - ruby-version: "3.1"
            ar-gemfile: "activerecord8.0"
          - ruby-version: "3.0"
            ar-gemfile: "activerecord7.1"
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          cp gemfiles/Gemfile.${{ matrix.ar-gemfile }} Gemfile
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rspec

      - name: Run RuboCop
        run: bundle exec rubocop
